@startuml





/' Objects '/

class ZoneAUrbaniser {
	+ZoneAUrbaniser(int num, const std::string& prop, const Polygone<int, float>& forme)
	+surfaceConstructible() : float {query}
	+operator<<(std::ostream& os, const ZoneAUrbaniser& zau) : std :: ostream&
	+setType(const std::string& type) : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
